# Generated by Django 4.1.1 on 2022-10-04 03:42

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('regnumber', models.IntegerField(default=students.models.random_reg_number, max_length=10)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
