# Generated by Django 4.1.1 on 2022-10-04 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students_date_updated_alter_students_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='students',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
